import { faker } from '@faker-js/faker';
import { CREDIT_CARDS } from '../constants';
import CreditCard from '../services/types/creditCard';

export const CreditCardFactory = {
  /**
   * Method that gets the credit card number given the card type requested.
   * @param card: The card type the user wants to use
   * @returns credit card number for the card type requested.
   */
  getCreditCardNumber(creditCardType: string): string {
    let cardNumber: string;
    switch (creditCardType) {
      case 'American Express':
        cardNumber = CREDIT_CARDS.AMEX;
        break;
      case 'Visa':
        cardNumber = CREDIT_CARDS.VISA;
        break;
      case 'MasterCard':
        cardNumber = CREDIT_CARDS.MASTERCARD;
        break;
      case 'Discover':
        cardNumber = CREDIT_CARDS.DISCOVER;
        break;
      default:
        throw new Error(
          `${creditCardType} is not a valid credit card type (Visa, Discover, American Express, MasterCard).`
        );
    }
    return cardNumber;
  },

  /**
   * Creates a credit card object
   * @param {cardNumber} paramater that is passed in by the User in a test case. User can decide to use a Visa, Discover, etc. otherwise "Visa" is used as default
   * for older test cases
   * @returns {CreditCard}
   */
  createCreditCard(creditCardType = 'Visa'): CreditCard {
    const cardNumber = this.getCreditCardNumber(creditCardType);
    const expirationDate = faker.date.future(5);
    const expirationMonth = (expirationDate.getMonth() + 1)
      .toString()
      .padStart(2, '0');
    const expirationYear = expirationDate.getFullYear().toString().slice(-2);

    return {
      cardNumber,
      // Ternary operator will assign a 4 digit CVV if American Express is being used. Otherwise it will be a 3 digit random number generated by Faker.git
      cvv:
        cardNumber === CREDIT_CARDS.AMEX
          ? '1234'
          : faker.finance.creditCardCVV(),
      expirationMonth,
      expirationYear,
      postalCode: faker.address.zipCode('#####'),
    };
  },
};

export default CreditCardFactory;
